package com.nano.hr.bs;

import java.util.HashMap;

public class TwoDimentionalArrayToMap
{
	public static final String SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS = "ShortTermLeaveplanning.TotalHours";
	public static final String SHORT_TERM_LEAVEPLANNING_CURRENT_ACCOUNT = "ShortTermLeaveplanning.CurrentAccount";
	public static final String SHORT_TERM_LEAVEPLANNING_BOUGHT_EVT = "ShortTermLeaveplanning.BoughtEVT";
	public static final String SHORT_TERM_LEAVEPLANNING_INDEPENDANT_EVT = "ShortTermLeaveplanning.IndependantEVT";
	public static final String SHORT_TERM_LEAVEPLANNING_LEGAL_DAY_OFF = "ShortTermLeaveplanning.LegalDayOff";

	public static final String SHORT_TERM_LEAVE_REPORTING_CURRENT_ACCOUNT = "ShortTermLeaveReporting.CurrentAccount";
	public static final String SHORT_TERM_LEAVE_REPORTING_DEPENDANT_EVT = "ShortTermLeaveReporting.DependantEVT";
	public static final String SHORT_TERM_LEAVE_REPORTING_AGEDEPENDANTDAYOF = "ShortTermLeaveReporting.AgeDependantDayOf";
	public static final String SHORT_TERM_LEAVE_REPORTING_BONUS4BEINGPRESENT = "ShortTermLeaveReporting.Bonus4BeingPresent";
	public static final String SHORT_TERM_LEAVE_REPORTING_TOTALHOURS = "ShortTermLeaveReporting.TotalHours";
	public static final String SHORT_TERM_LEAVE_REPORTING_TOTALEURO = "ShortTermLeaveReporting.TotalEuro";

	public static final String BENEFIT_SHOP_OPTIONS_CARELEAVE = "BenefitShopOptions.CareLeave";
	public static final String BENEFIT_SHOP_OPTIONS_EVT = "BenefitShopOptions.EVT";
	public static final String BENEFIT_SHOP_OPTIONS_PAYOUT = "BenefitShopOptions.PayOut";
	public static final String BENEFIT_SHOP_OPTIONS_TOR = "BenefitShopOptions.TOR";
	public static final String BENEFIT_SHOP_OPTIONS_SABBATICAL = "BenefitShopOptions.Sabbatical";
	public static final String BENEFIT_SHOP_OPTIONS_PARENTALLEAVE = "BenefitShopOptions.ParentalLeave";
	public static final String BENEFIT_SHOP_OPTIONS_STUDY = "BenefitShopOptions.Study";

	public static final String BENEFIT_SHOP_OPTIONS_CARELEAVE_EURO = "BenefitShopOptions.CareLeave_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_EVT_EURO = "BenefitShopOptions.EVT_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_PAYOUT_EURO = "BenefitShopOptions.PayOut_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_PAYOUT_MONTH = "BenefitShopOptions.PayOut_Month";
	public static final String BENEFIT_SHOP_OPTIONS_TOR_EURO = "BenefitShopOptions.TOR_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_SABBATICAL_EURO = "BenefitShopOptions.Sabbatical_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_PARENTALLEAVE_EURO = "BenefitShopOptions.ParentalLeave_EURO";
	public static final String BENEFIT_SHOP_OPTIONS_STUDY_EURO = "BenefitShopOptions.Study_EURO";

	public static final String RESERVED_LEAVE_CARELEAVE = "ReservedLeave.CareLeave";
	public static final String RESERVED_LEAVE_SABBATICAL = "ReservedLeave.Sabbatical";
	public static final String RESERVED_LEAVE_TOR = "ReservedLeave.TOR";
	public static final String RESERVED_LEAVE_PARENTALLEAVE = "ReservedLeave.ParentalLeave";
	public static final String RESERVED_LEAVE_STUDY = "ReservedLeave.Study";
	public static final String RESERVED_LEAVE_TOTALHOURS = "ReservedLeave.TotalHours";
	
	public static final String BENEFIT_SHOP_PSEUDO_AFAS_CODE_FOR_UPLOADS = "999";
	public static final String BENEFIT_SHOP_AFASCODE_BONUS4BEINGPRESENT = "275";
	public static final String BENEFIT_SHOP_AFASCODE_AGEDEPENDANTDAYOF = "120";
	public static final String BENEFIT_SHOP_AFASCODE_SURPLUS_CURRENT_ACCOUNT = "350";
	public static final String BENEFIT_SHOP_AFASCODE_PAYOUT = "510";
	public static final String BENEFIT_SHOP_AFASCODE_DEPENDANT_EVT = "250";
	public static final String BENEFIT_SHOP_AFASCODE_BOUGHT_EVT = "210";
	public static final String BENEFIT_SHOP_AFASCODE_TOR = "520";
	public static final String BENEFIT_SHOP_AFASCODE_STUDY = "550";
	public static final String BENEFIT_SHOP_AFASCODE_SABBATICAL = "530";
	public static final String BENEFIT_SHOP_AFASCODE_CARELEAVE = "560";
	public static final String BENEFIT_SHOP_AFASCODE_PARENTALLEAVE = "540";

	public static final String[][] FIELDCODEREADMAPPING = new String[][]{
		{SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS,SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS},
		{SHORT_TERM_LEAVEPLANNING_LEGAL_DAY_OFF,"100"},
		{SHORT_TERM_LEAVEPLANNING_INDEPENDANT_EVT,"200"},
		{SHORT_TERM_LEAVEPLANNING_BOUGHT_EVT,BENEFIT_SHOP_AFASCODE_BOUGHT_EVT},
		{SHORT_TERM_LEAVEPLANNING_CURRENT_ACCOUNT,"300"},
		{SHORT_TERM_LEAVE_REPORTING_AGEDEPENDANTDAYOF,BENEFIT_SHOP_AFASCODE_AGEDEPENDANTDAYOF},// BENEFIT_SHOP_AFASCODE_AGEDEPENDANTDAYOF
		{SHORT_TERM_LEAVE_REPORTING_DEPENDANT_EVT,BENEFIT_SHOP_AFASCODE_DEPENDANT_EVT},
		{SHORT_TERM_LEAVE_REPORTING_BONUS4BEINGPRESENT,BENEFIT_SHOP_AFASCODE_BONUS4BEINGPRESENT},// BENEFIT_SHOP_AFASCODE_BONUS4BEINGPRESENT
		{SHORT_TERM_LEAVE_REPORTING_CURRENT_ACCOUNT,BENEFIT_SHOP_AFASCODE_SURPLUS_CURRENT_ACCOUNT},

		{SHORT_TERM_LEAVE_REPORTING_TOTALEURO,SHORT_TERM_LEAVE_REPORTING_TOTALEURO},
		{SHORT_TERM_LEAVE_REPORTING_TOTALHOURS,SHORT_TERM_LEAVE_REPORTING_TOTALHOURS},

		{RESERVED_LEAVE_TOTALHOURS,RESERVED_LEAVE_TOTALHOURS},
		{RESERVED_LEAVE_CARELEAVE,BENEFIT_SHOP_AFASCODE_CARELEAVE},
		{RESERVED_LEAVE_TOR,BENEFIT_SHOP_AFASCODE_TOR},
		{RESERVED_LEAVE_SABBATICAL,BENEFIT_SHOP_AFASCODE_SABBATICAL},
		{RESERVED_LEAVE_PARENTALLEAVE,BENEFIT_SHOP_AFASCODE_PARENTALLEAVE},
		{RESERVED_LEAVE_STUDY,BENEFIT_SHOP_AFASCODE_STUDY}
		};

	public static final String[][] FIELDCODEEDITMAPPING = new String[][]{
		{BENEFIT_SHOP_OPTIONS_EVT,BENEFIT_SHOP_AFASCODE_BOUGHT_EVT},
		{BENEFIT_SHOP_OPTIONS_PAYOUT,BENEFIT_SHOP_AFASCODE_PAYOUT},
		{BENEFIT_SHOP_OPTIONS_TOR,BENEFIT_SHOP_AFASCODE_TOR},
		{BENEFIT_SHOP_OPTIONS_SABBATICAL,BENEFIT_SHOP_AFASCODE_SABBATICAL},
		{BENEFIT_SHOP_OPTIONS_PARENTALLEAVE,BENEFIT_SHOP_AFASCODE_PARENTALLEAVE},
		{BENEFIT_SHOP_OPTIONS_STUDY,BENEFIT_SHOP_AFASCODE_STUDY},
		{BENEFIT_SHOP_OPTIONS_CARELEAVE,BENEFIT_SHOP_AFASCODE_CARELEAVE}
		};
	
	private static String[][] FIELDTOTOTALMAPPING = new String[][]{
		{RESERVED_LEAVE_CARELEAVE,RESERVED_LEAVE_TOTALHOURS},
		{RESERVED_LEAVE_PARENTALLEAVE,RESERVED_LEAVE_TOTALHOURS},
		{RESERVED_LEAVE_SABBATICAL,RESERVED_LEAVE_TOTALHOURS},
		{RESERVED_LEAVE_STUDY,RESERVED_LEAVE_TOTALHOURS},
		{RESERVED_LEAVE_TOR,RESERVED_LEAVE_TOTALHOURS},

		{SHORT_TERM_LEAVEPLANNING_BOUGHT_EVT,SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS},
		{SHORT_TERM_LEAVEPLANNING_CURRENT_ACCOUNT,SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS},
		{SHORT_TERM_LEAVEPLANNING_INDEPENDANT_EVT,SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS},
		{SHORT_TERM_LEAVEPLANNING_LEGAL_DAY_OFF,SHORT_TERM_LEAVEPLANNING_TOTAL_HOURS},

		{SHORT_TERM_LEAVE_REPORTING_AGEDEPENDANTDAYOF,SHORT_TERM_LEAVE_REPORTING_TOTALHOURS},
		{SHORT_TERM_LEAVE_REPORTING_BONUS4BEINGPRESENT,SHORT_TERM_LEAVE_REPORTING_TOTALHOURS},
		{SHORT_TERM_LEAVE_REPORTING_CURRENT_ACCOUNT,SHORT_TERM_LEAVE_REPORTING_TOTALHOURS},
		{SHORT_TERM_LEAVE_REPORTING_DEPENDANT_EVT,SHORT_TERM_LEAVE_REPORTING_TOTALHOURS},
		{"€"+SHORT_TERM_LEAVE_REPORTING_AGEDEPENDANTDAYOF,SHORT_TERM_LEAVE_REPORTING_TOTALEURO},
		{"€"+SHORT_TERM_LEAVE_REPORTING_BONUS4BEINGPRESENT,SHORT_TERM_LEAVE_REPORTING_TOTALEURO},
		{"€"+SHORT_TERM_LEAVE_REPORTING_CURRENT_ACCOUNT,SHORT_TERM_LEAVE_REPORTING_TOTALEURO},
		{"€"+SHORT_TERM_LEAVE_REPORTING_DEPENDANT_EVT,SHORT_TERM_LEAVE_REPORTING_TOTALEURO}
	};


	public static final HashMap<String, String> CODEBYREADFIELD = new HashMap<String, String>(){{
        for (String[] mapping : FIELDCODEREADMAPPING){
        	put(mapping[0],mapping[1]);
        }
	}};

	public static final HashMap<String, String> READFIELDBYCODE = new HashMap<String, String>(){{
        for (String[] mapping : FIELDCODEREADMAPPING){
        	put(mapping[1],mapping[0]);
        }
	}};
	public static void main(String[] args)
	{
		// TODO Auto-generated method stub

	}

}
